Create airdrop contract
homiesglobal/homiesglobal pull request #22
Opened 2022-02-21 22:20 UTC by Bezaeel

This PR closes #3

2022-02-22 18:06 UTC, e-mubaraq commented on modules/contracts/test/Airdrop.test.ts
> +  let addr2: SignerWithAddress;
This addr2 was not really used in these tests other than being added as a recipient. There were not checks done with it.

2022-02-23 09:10 UTC, perfectmak requested changes
Nice work. I left a couple 😅 of comments and changes

2022-02-23 09:10 UTC, perfectmak commented on modules/contracts/contracts/AirDrop.sol
> +        homieToken.transferFrom(msg.sender, recipient, amountToBeClaimed);
Two things here:

1. We should check the returned bool of the `transferFrom` (or `transfer`) function before confirming the transfer was successful. And only on success should we emit the token claimed.

2. If I remember correctly, we want to transfer from the Airdrop Contract's balance to the sender's account.
So this `transferFrom(msg.sender, recipient)` call won't work.

First, we should update the signature of the Claim Token function to not have a `recipient` address. The recipient is the `msg.sender`.
Then, we should be doing something like `transferFrom(address(this), msg.sender, amountToBeClaimed)`.

2022-02-23 18:49 UTC, Bezaeel commented on modules/contracts/contracts/AirDrop.sol
> +        homieToken.transferFrom(msg.sender, recipient, amountToBeClaimed);
more excellent, this has been resolved

2022-02-23 21:08 UTC, Bezaeel commented on modules/contracts/contracts/AirDrop.sol
> +        homieToken.transferFrom(msg.sender, recipient, amountToBeClaimed);
quick one, on deployment, how will the amount be specified? hard coded or ?

2022-02-24 06:06 UTC, perfectmak commented on modules/contracts/contracts/AirDrop.sol
> +        homieToken.transferFrom(msg.sender, recipient, amountToBeClaimed);
Yes, hard coded should be fine.

2022-02-25 21:26 UTC, perfectmak requested changes
One last comments from my end. Let me know

2022-02-25 21:26 UTC, perfectmak commented on modules/contracts/contracts/AirDrop.sol
> +        homieToken.approve(address(this), airdropBalance);
You shouldn't need this lines. 

You should modify the deploy script to have the Airdrop Contract get sent the required amount for airdrops.

Then you should use the `transfer` function instead of the `transferFrom` function on the HomieToken and it should work. @Bezaeel

2022-03-01 22:11 UTC, perfectmak approved these changes
LGTM 🚀

2022-03-02 00:57 UTC, georgeokez commented on modules/contracts/scripts/deploy.ts
>    console.log("Greeter deployed to:", greeter.address);
Is there a need for all these console logs, if they were added for debugging purposes I think they can be removed?

2022-03-02 00:58 UTC, georgeokez approved these changes

2022-03-02 23:17 UTC, merged